In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'col1':[1,2,3,4,5],
              'col2':[45,56,67,34,34],
              'col3':"sudhanshu kumar krish ineuron one"
             })

col1  col2                               col3
0     1    45  sudhanshu kumar krish ineuron one
1     2    56  sudhanshu kumar krish ineuron one
2     3    67  sudhanshu kumar krish ineuron one
3     4    34  sudhanshu kumar krish ineuron one
4     5    34  sudhanshu kumar krish ineuron one

In [3]:
"sudhanshu kumar krish ineuron one".split()


['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [5]:
df=pd.DataFrame({'col1':[1,2,3,4,5],
              'col2':[45,56,67,34,34],
              'col3':"sudhanshu kumar krish ineuron one".split()
             })

In [6]:
df

col1  col2       col3
0     1    45  sudhanshu
1     2    56      kumar
2     3    67      krish
3     4    34    ineuron
4     5    34        one

In [8]:
df["col4"]=df["col1"]**2

In [9]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     4
2     3    67      krish     9
3     4    34    ineuron    16
4     5    34        one    25

In [10]:
df["col5"]=df["col3"].str[0]

In [11]:
df

col1  col2       col3  col4 col5
0     1    45  sudhanshu     1    s
1     2    56      kumar     4    k
2     3    67      krish     9    k
3     4    34    ineuron    16    i
4     5    34        one    25    o

## apply function 

In [14]:
def test(a):
    return a*a

In [15]:
df["col4_4"]= df["col1"].apply(test)

In [16]:
df

col1  col2       col3  col4 col5  col4_4
0     1    45  sudhanshu     1    s       1
1     2    56      kumar     4    k       4
2     3    67      krish     9    k       9
3     4    34    ineuron    16    i      16
4     5    34        one    25    o      25

In [19]:
def test1(a):
    if a=="s":
        return a
    else:
        return "z"

In [20]:
df["col6"] = df["col5"].apply(test1)

In [22]:
df

col1  col2       col3  col4 col5  col4_4 col6
0     1    45  sudhanshu     1    s       1    s
1     2    56      kumar     4    k       4    z
2     3    67      krish     9    k       9    z
3     4    34    ineuron    16    i      16    z
4     5    34        one    25    o      25    z

In [24]:
df["col6_6"] = df["col5"].apply(lambda a:"s" if a=="s" else "z")

In [25]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6
0     1    45  sudhanshu     1    s       1    s      s
1     2    56      kumar     4    k       4    z      z
2     3    67      krish     9    k       9    z      z
3     4    34    ineuron    16    i      16    z      z
4     5    34        one    25    o      25    z      z

In [28]:
df["col7"] = df["col3"].apply(len)

In [29]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45  sudhanshu     1    s       1    s      s     9
1     2    56      kumar     4    k       4    z      z     5
2     3    67      krish     9    k       9    z      z     5
3     4    34    ineuron    16    i      16    z      z     7
4     5    34        one    25    o      25    z      z     3

In [33]:
import math

In [39]:
df["col8"]=df["col2"].apply(math.log)

In [40]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45  sudhanshu     1    s       1    s      s     9  3.806662
1     2    56      kumar     4    k       4    z      z     5  4.025352
2     3    67      krish     9    k       9    z      z     5  4.204693
3     4    34    ineuron    16    i      16    z      z     7  3.526361
4     5    34        one    25    o      25    z      z     3  3.526361

## numpy

In [41]:
import numpy as np

In [42]:
 l=[1,2,3,4,"sudh"]

In [43]:
type(l)

list

In [44]:
np.array(l)

array(['1', '2', '3', '4', 'sudh'], dtype='<U11')

In [45]:
type(np.array(l))

numpy.ndarray

In [46]:
np.array([1,2,3,4,5.0])   # this will convert all int number into float number

array([1., 2., 3., 4., 5.])

In [49]:
a=np.array([[1,2],[3,4]])

In [50]:
a

array([[1, 2],
       [3, 4]])

In [51]:
a[1][1]

4

In [52]:
a[1][0]

3

In [53]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [54]:
np.array([1,2,3,4],ndmin=3)   # ndmin is a diamention of array

array([[[1, 2, 3, 4]]])

In [55]:
a=np.array([1,2,3,4], ndmin=3)

In [56]:
a[0][0][0]

1

In [57]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [58]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [60]:
np.mat([1,2,3,4,5])    # matrix try to return 2D array

matrix([[1, 2, 3, 4, 5]])

In [61]:
a=[1,2,3,4,5]
np.array(a)

array([1, 2, 3, 4, 5])

In [62]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [63]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [64]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [66]:
np.asanyarray(np.mat(a))  # not converting in to array 
                          # asanyarray convert into array if it is not an array if it is array then it not convert 

matrix([[1, 2, 3, 4, 5]])

In [68]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [69]:
np.fromfunction(lambda i, j :i*j ,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [70]:
np.fromfunction(lambda i, j :i*j ,(4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [71]:
np.mat(np.fromfunction(lambda i, j :i*j ,(4,4)))

matrix([[0., 0., 0., 0.],
        [0., 1., 2., 3.],
        [0., 2., 4., 6.],
        [0., 3., 6., 9.]])

In [72]:
np.fromfunction(lambda i,j,z:i*j*z,(3,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [74]:
np.fromfunction(lambda i,j,z,p:i*j*z*p,(4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [84]:
a=np.fromfunction(lambda i,j:i*j,(3,2),dtype=int)

In [85]:
a

array([[0, 0],
       [0, 1],
       [0, 2]])

In [86]:
a.ndim


2

In [106]:
a=np.fromfunction(lambda i,j,z:i*j*z,(4,3,2),dtype=int)

In [113]:
a.reshape(4,-1)   # by default it take -1 as 6 for converting to 2D  4 x 6 = 24
                  #

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [114]:
a.reshape(4,-13434)  # its for any -ve number

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [115]:
a.reshape(2,4,-234)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [107]:
a.reshape(12,2)  # by reshape we can change the dimention of array 

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [112]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [110]:
a=a.reshape(6,4)

In [111]:
pd.DataFrame(a)  # then we can convert into dataframe

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [87]:
a.size

6

In [88]:
a.shape

(3, 2)

In [89]:
a.dtype

dtype('int32')

In [90]:
a

array([[0, 0],
       [0, 1],
       [0, 2]])

In [91]:
import pandas as pd

In [92]:
pd.DataFrame(a)  # to convert into dataframe data must be in 2D array 

0  1
0  0  0
1  0  1
2  0  2

In [94]:
np.random.rand(100,4)   # genrate 100 *4 values

array([[0.40015088, 0.94676585, 0.76866759, 0.44250768],
       [0.32576441, 0.71474823, 0.59743085, 0.12021548],
       [0.78285339, 0.50274519, 0.59108488, 0.61725267],
       [0.79731363, 0.05918488, 0.04728443, 0.76791066],
       [0.25771581, 0.71608328, 0.9366783 , 0.04713937],
       [0.2450684 , 0.58162206, 0.05924757, 0.77962959],
       [0.39720338, 0.936356  , 0.76232668, 0.01942759],
       [0.18355627, 0.23834749, 0.26994354, 0.69205555],
       [0.70041865, 0.74991993, 0.22387166, 0.70321528],
       [0.90841048, 0.50363482, 0.86815569, 0.30827924],
       [0.15077925, 0.51697497, 0.16442803, 0.48920249],
       [0.70046994, 0.41488847, 0.62378203, 0.47724382],
       [0.80951553, 0.37144088, 0.92540701, 0.33064616],
       [0.23151258, 0.49890472, 0.82096037, 0.92381491],
       [0.531321  , 0.1159138 , 0.94755913, 0.02383686],
       [0.63889329, 0.59892907, 0.80713213, 0.14484844],
       [0.5487499 , 0.42242709, 0.68219365, 0.6658568 ],
       [0.24680604, 0.5631291 ,

In [99]:
np.random.randint(4,50)   # genrate random int btn 4 to 50

32

In [101]:
np.random.randn(4,5) # randn give numbers which avrage is 0 

array([[ 0.3021197 , -2.08131185,  0.54308423,  1.1296945 , -0.78919092],
       [-0.51091793, -0.62212985,  0.50725123,  0.00708717, -1.55050623],
       [ 1.06955701,  0.26257614,  0.89090405, -1.01374775, -0.26222629],
       [-0.27568747, -0.84565405, -0.57429977, -1.01770344,  0.84433764]])

In [103]:
pd.DataFrame(np.random.randn(4,5)) 

0         1         2         3         4
0  1.968081  1.218830 -0.580374  0.463307  0.426983
1 -0.178829 -1.331622  0.069544 -2.278775 -2.057417
2  1.831350  0.479438  0.491179 -0.305171 -0.385070
3  0.267739 -0.959690  0.603533  0.123590 -0.462238

In [116]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [118]:
list(range(4,10,.2))   # it required step as a integer

TypeError: 'float' object cannot be interpreted as an integer

In [117]:
np.arange(4,10,0.2)    # we can use float value in step , first and last values in numpy nrange

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [119]:
a1=np.arange(4,10,0.2) 

In [120]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [121]:
arr= np.random.rand(4,5)

In [122]:
arr

array([[0.89042646, 0.72101041, 0.08068836, 0.56367251, 0.63406825],
       [0.23400094, 0.16108789, 0.50114944, 0.56811474, 0.29440295],
       [0.85424989, 0.54692089, 0.67662044, 0.21273575, 0.94238576],
       [0.94091812, 0.84793763, 0.28843599, 0.91856608, 0.7714906 ]])

In [124]:
arr[arr > 0.5]

array([0.89042646, 0.72101041, 0.56367251, 0.63406825, 0.50114944,
       0.56811474, 0.85424989, 0.54692089, 0.67662044, 0.94238576,
       0.94091812, 0.84793763, 0.91856608, 0.7714906 ])

In [125]:
arr

array([[0.89042646, 0.72101041, 0.08068836, 0.56367251, 0.63406825],
       [0.23400094, 0.16108789, 0.50114944, 0.56811474, 0.29440295],
       [0.85424989, 0.54692089, 0.67662044, 0.21273575, 0.94238576],
       [0.94091812, 0.84793763, 0.28843599, 0.91856608, 0.7714906 ]])

In [130]:
arr[[1,2],[2]]

array([0.50114944, 0.67662044])

In [131]:
arr= np.random.rand(8,5)

In [132]:
arr

array([[0.99533721, 0.62651174, 0.1478108 , 0.42051416, 0.75286233],
       [0.53294614, 0.0347747 , 0.19773058, 0.6011246 , 0.39071092],
       [0.23073318, 0.33454578, 0.10774392, 0.44333906, 0.48141184],
       [0.16190829, 0.735097  , 0.83675674, 0.576277  , 0.74708425],
       [0.79201034, 0.13087452, 0.75787029, 0.63378613, 0.82461223],
       [0.34413782, 0.48647196, 0.88175039, 0.70828141, 0.31983316],
       [0.83017815, 0.61248412, 0.37919503, 0.05919567, 0.19731626],
       [0.21618641, 0.21617435, 0.40675935, 0.1083946 , 0.23067053]])

In [136]:
arr[1:8, 0:3]

array([[0.53294614, 0.0347747 , 0.19773058],
       [0.23073318, 0.33454578, 0.10774392],
       [0.16190829, 0.735097  , 0.83675674],
       [0.79201034, 0.13087452, 0.75787029],
       [0.34413782, 0.48647196, 0.88175039],
       [0.83017815, 0.61248412, 0.37919503],
       [0.21618641, 0.21617435, 0.40675935]])

In [140]:
a2=arr[1:7,[0,1,2,3]]

In [141]:
a2

array([[0.53294614, 0.0347747 , 0.19773058, 0.6011246 ],
       [0.23073318, 0.33454578, 0.10774392, 0.44333906],
       [0.16190829, 0.735097  , 0.83675674, 0.576277  ],
       [0.79201034, 0.13087452, 0.75787029, 0.63378613],
       [0.34413782, 0.48647196, 0.88175039, 0.70828141],
       [0.83017815, 0.61248412, 0.37919503, 0.05919567]])

In [149]:
a2[0][0] = 132

In [150]:
a2

array([[1.32000000e+02, 3.47747010e-02, 1.97730576e-01, 6.01124600e-01],
       [2.30733179e-01, 3.34545776e-01, 1.07743916e-01, 4.43339063e-01],
       [1.61908286e-01, 7.35096999e-01, 8.36756737e-01, 5.76277005e-01],
       [7.92010338e-01, 1.30874523e-01, 7.57870293e-01, 6.33786127e-01],
       [3.44137825e-01, 4.86471959e-01, 8.81750389e-01, 7.08281414e-01],
       [8.30178153e-01, 6.12484123e-01, 3.79195026e-01, 5.91956714e-02]])

In [152]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

In [153]:
a

array([[1, 2],
       [3, 4]])

In [154]:
b

array([[2, 3],
       [4, 5]])

In [155]:
a*b    # element multiplication 

array([[ 2,  6],
       [12, 20]])

In [157]:
m=a@b    # @ give matrix multiplication condition is column of first and row of second must be same

In [158]:
m

array([[10, 13],
       [22, 29]])

In [159]:
m/0

C:\Users\aakas\AppData\Local\Temp\ipykernel_9916\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])